### ISSUE TITLE
Error generating fonts

### ISSUE THREAD

**Issue by JamesMilnerUK** [jvanaert/gulp-webfont#7]
Hey, thanks for the plugin, appreciated.

I'm struggling to get it to run however. On `gulp fonts` I receive an error:

```
17:22:13] Starting 'fonts'...
Font icons with 3 glyphs created.
[17:22:13] icons.eot
[17:22:13] icons.woff
[17:22:13] icons.ttf
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/tmp/d-11766-20220-1gyb7h8.p35drc0udi/icons.eot'
    at Error (native)
```

Here is my code:

```javascript
var webfont_config = {
  // dest: './../public/css/fonts',
  // destCss: './../public/css/external',
  options: {
    font: 'three-d-repo',
    fontFilename: 'three-d-repo',
    htmlDemo: false
  }
}

gulp.task('fonts', function () {
  return gulp.src('./../icons/*.svg')
    .pipe(webfont(webfont_config))
    .pipe(print())
    .pipe(gulp.dest("./")))
});
```

Any ideas what might be wrong?

**Comment by JamesMilnerUK** [comment]
adding:

```
  types:'woff2,woff,ttf,svg'
```
fixed the issue. Seems maybe there is a problem with eot  ?

**Comment by cyntss** [comment]
I'm having the same issue and it solves by removing `eot` from the options. Any way to fix this and have `eot` extension?

**Comment by JamesMilnerUK** [comment]
I never came to any fix unfortunately. Here's the list of places eot is referenced in the source code, maybe there's some hints in there ? https://github.com/jvanaert/gulp-webfont/search?utf8=%E2%9C%93&q=eot&type=

**Comment by cyntss** [comment]
@JamesMilnerUK thanks, I will have a look. In the worst case i will have to just switch to Grunt-webfont. It works perfectly fine there, and at least in our project we still don't use any build system, so we have that option (although I prefer Gulp 😢 )
